services:
  rest-book-server:
    build:
      context: .
      dockerfile: deployments/rest-books-server/Dockerfile
    container_name: rest-books-server
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      CONFIG_FILE: /app/configs/rest-books-server.yaml
    networks:
      - books_network

  db:
    image: postgres:15
    container_name: books_db
    environment:
      POSTGRES_USER: books
      POSTGRES_PASSWORD: books
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - books_network

volumes:
  db_data:

networks:
  books_network:
